afteruts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
]

main/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
]

story7/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8, name='story8'),
    path('data', views.books_func, name='data'),
]

story9/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.story9login, name='login'),
    path('signup/', views.story9signup, name='signup'),
    path('logout/', views.story9logout, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models
from django.contrib.auth.models import User

class Story9(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

story9/forms.py
from django import forms
from .models import Story9
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class SignUpForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password_first = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_again = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        password_one = self.cleaned_data.get('password_first')
        password_two = self.cleaned_data.get('password_again')
        if password_one != password_two:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email_address)
        if qs.exists():
            raise forms.ValidationError("The email address you've chosen is already registered.")
        return email_address

main/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

story7/views.py
from django.shortcuts import render

def story7(request):
    return render(request, 'story7.html')

story8/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import requests
import json

def story8(request):
    response = {}
    return render(request, 'story8.html', response)

def books_func(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    result = requests.get(url)
    data = json.loads(result.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from .models import Story9
from .forms import LoginForm, SignUpForm

User = get_user_model()

def story9login(request):
    form = LoginForm(request.POST or None)
    context = {
        'form': form
    }
    print(request.user.is_authenticated)
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            print("ERROR")
    return render(request, 'story9login.html', context=context)

def story9signup(request):
    form = SignUpForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password_first")
        User.objects.create_user(username, email, password)
        return HttpResponseRedirect('/story9')   
    return render(request, 'story9signup.html', context=context)

def story9logout(request):
    logout(request)
    return render(request, 'main.html')

main/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="icon" href="{% static 'logo.png' %}">
    <title>Another Jaja's Story</title>
</head>
<body>
    <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
        <li id="username"><a href="#"><span class="glyphicon glyphicon-user"></span>  {{ user.username }}</a></li>
        <li id="logout"><a href="{% url 'story9:logout' %}"><span class="glyphicon glyphicon-log-out"></span>  Log out</a></li>
        
        {% else %}
        <li id="signup"><a href="{% url 'story9:signup' %}"><span class="glyphicon glyphicon-user"></span>  Sign up</a></li>
        <li id="login"><a href="{% url 'story9:login' %}"><span class="glyphicon glyphicon-log-in"></span>  Log in</a></li>
        
        {% endif %}
    </ul>

    {% if user.is_authenticated %}
    <h1 class="ml10">Hello, {{user.username}}...</h1>
    {% endif %}

    <h1 class="ml10">
        <span class="text-wrapper">
            <span class="letters">✨ Welcome to Another Jaja's Story! ✨</span>
        </span>
    </h1>

    <div class="story">
        <h3><a href="/story7/">Story 7</a></h3>
    </div>

    <div class="story">
        <h3><a href="/story8/">Story 8</a></h3>
    </div>

    <!-- taken from https://tobiasahlin.com/moving-letters/#10 -->
    <script>
    var textWrapper = document.querySelector('.ml10 .letters');
    textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

    anime.timeline({loop: true})
    .add({
        targets: '.ml10 .letter',
        rotateY: [-90, 0],
        duration: 1300,
        delay: (el, i) => 45 * i
    }).add({
        targets: '.ml10',
        opacity: 0,
        duration: 1000,
        easing: "easeOutExpo",
        delay: 1000
    });
    </script>
</body>
</html>

story7/templates/story7.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="{% static 'jquery-3.5.1.js' %}"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'story7.css' %}">
    <script src="{% static 'story7.js' %}"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="icon" href="{% static 'logo.png' %}">
    <title>Story 7 - Jaja's Story</title>
</head>

<body>
    <div>
        <h1 id="back"><a href="/" style="text-decoration-color: #9671FC;">🔙</a></h1>
    </div>

    <div class="container-fluid">
        <div id="accordionActivities">
            <h3>Activities🙋‍♀️
                <span style="float: right;">
                    <button class="up" style="font-size: 15px;"><i class="fas fa-chevron-up"></i></button>
                    <button class="down" style="font-size: 15px;"><i class="fas fa-chevron-down"></i></button>
                </span>
            </h3>
            <div class="content">
                <ul>
                    <li>Kuliah</li>
                    <li>Sambat</li>
                    <li>Jadi staf PSDM</li>
                    <li>Jadi sabinya PTI</li>
                    <li>Ngurus Wisgan 2021</li>
                    <li>Bersedih-sedih</li>
                    <li>Bersenang-senang</li>
                </ul>
            </div>
        </div>
    
        <div id="accordionExperiences">
            <h3>Experiences👩‍🔧
                <span style="float: right;">
                    <button class="up" style="font-size: 15px;"><i class="fas fa-chevron-up"></i></button>
                    <button class="down" style="font-size: 15px;"><i class="fas fa-chevron-down"></i></button>
                </span>
            </h3>
            <div class="content">
                <ul>
                    <li>PJ SBF Gath 2019</li>
                    <li>Vice Manager of Finance Compfest 12</li>
                    <li>Staf Acara Wisgan 2020</li>
                    <li>Staf PSDM BEM Fasilkom UI 2020</li>
                    <li>Probation member of Finance, Governance, and Legality AIESEC in UI</li>
                </ul>
            </div>
        </div>
    
        <div id="accordionAchievement">
            <h3>Achievement🏆
                <span style="float: right;">
                    <button class="up" style="font-size: 15px;"><i class="fas fa-chevron-up"></i></button>
                    <button class="down" style="font-size: 15px;"><i class="fas fa-chevron-down"></i></button>
                </span>
            </h3>
            <div class="content">
                <ul>
                    <li>Ga ada-__-</li>
                </ul>
            </div>
        </div>
    
        <div id="accordionHappyPills">
            <h3>Happy Pills💕
                <span style="float: right;">
                    <button class="up" style="font-size: 15px;"><i class="fas fa-chevron-up"></i></button>
                    <button class="down" style="font-size: 15px;"><i class="fas fa-chevron-down"></i></button>
                </span>
            </h3>
            <div class="content">
                <ul>
                    <li>Metawin Opas-iamkajorn</li>
                    <li>Kim Seonho</li>
                    <li>Bokuto Koutarou</li>
                </ul>
            </div>
        </div>
    </div>
</body>
</html>

story8/templates/story8.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="{% static 'jquery-3.5.1.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'story8.css' %}">
    <script src="{% static 'story8.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="icon" href="{% static 'logo.png' %}">
    <title>Story 8 - Jaja's Story</title>
</head>

<body>
    <div id="back">
        <h1><a href="/" style="text-decoration-color: #9671FC;">🔙</a></h1>
    </div>

    <div id="divInput">
        <input class="form-control" id="keyword" type="text" placeholder="Enter keyword">
    </div>

    <div class="container" id="tabel">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col" style="width: 5px;">No</th>
                    <th scope="col" width="50px">Cover</th>
                    <th scope="col" width="40px">Title</th>
                    <th scope="col" width="40px">Author</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>

    <!-- <script type="text/javascript">
        $("#keyword").keyup(function() {
            var input_keyword = $("#keyword").val();
            // console.log(input_keyword);

            if (input_keyword.length) {
                $.ajax({
                url: 'https://www.googleapis.com/books/v1/volumes?q=' + input_keyword,
                success: function(data) {
                    var all_items = data.items;
                    // console.log(data);
                    $("#books_list").empty();
                    for (i=0; i<all_items.length; i++) {
                        var image = all_items[i].volumeInfo.imageLinks.smallThumbnail;
                        var title = all_items[i].volumeInfo.title;
                        var author = all_items[i].volumeInfo.authors;
                        // $("#books_list").append("<li>" + title + "<br><img src=" + image + "></li>");
                        $("#books_list").append("<li><img src=" + image + ">" + title + author + "</li>");
                    }
                }
            });
            }
            $("#books_list").empty();
        });
    </script> -->
</body>
</html>

story9/templates/story9login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="{% static 'jquery-3.5.1.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'story9.css' %}">
    <script src="{% static 'story9.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="icon" href="{% static 'logo.png' %}">
    <title>Login - Jaja's Story</title>
</head>

<body>
    <div id="back">
        <h1><a href="/" style="text-decoration-color: #9671FC;">🔙</a></h1>
    </div>

    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary" style="background-color: #C5A8F9;">Log in</button>
            </form>
        </div>
    </div>

    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8">
            <h5 style="color: #9671FC;">Don't have an account? <a href="{% url 'story9:signup'%}">Sign up</a></h5>
        </div>        
    </div>
</body>
</html>

story9/templates/story9signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="{% static 'jquery-3.5.1.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'story9.css' %}">
    <script src="{% static 'story9.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="icon" href="{% static 'logo.png' %}">
    <title>Sign Up - Jaja's Story</title>
</head>

<body>
    <div id="back">
        <h1><a href="/" style="text-decoration-color: #9671FC;">🔙</a></h1>
    </div>
    
    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary" style="background-color: #C5A8F9;">Sign up</button>
            </form>
        </div>        
    </div>
    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8">
            <h5 style="color: #9671FC;">Already have an account? <a href="{% url 'story9:login'%}">Log in</a></h5>
        </div>   
    </div>

</body>
</html>